Further information at: https://documen.tician.de/pycuda/array.html

In [1]:
!pip install pycuda

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.7 MB 5.0 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 69 kB 9.8 MB/s 
     |████████████████████████████████| 78 kB 8.3 MB/s 
  Created wheel for pycuda: filename=pycuda-2021.1-cp37-cp37m-linux_x86_64.whl size=626634 sha256=fc864e235327aacfcfd752bb81d9cd7eb7baa6510a374a84f2a83bcfa2328bee
  Stored in directory: /root/.cache/pip/wheels/c4/ef/49/dc6a5feb8d980b37c83d465ecab24949a6aa19458522a9e001
  Created wheel for pytools: filename=pytools-2022.1.9-py2.py3-none-any.whl size=64666 sha256=ade763119a1ea17748bcdfc51fe826c10d45a93c51a5af16054c4fa46df50a94
  Stored in directory: /root/.cache/pip/wheels/11/d8/85/01a8cf50977badf2da880865124b159b112b861655a9b631d3
Successfully built pycuda pytools


In [2]:
import numpy as np

In [3]:
import pycuda.autoinit
import pycuda.gpuarray as gpuarray
import pycuda.cumath

In [4]:
h_x = np.zeros((32, 32), dtype = np.float32)
h_x[0, 0] = 11
h_x[2, 31] = -4

d_x = pycuda.gpuarray.to_gpu(h_x)

h_y = d_x.get()
print(h_y)

[[11.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0. -4.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]


In [5]:
d_x = gpuarray.zeros((32, 32), np.float32)
print(d_x)

d_y = gpuarray.empty((32, 32), np.float32)
print(d_y)

d_z = gpuarray.empty_like(d_x)
print(d_z)

d_w = gpuarray.zeros_like(d_x)
print(d_w)

d_h = gpuarray.ones_like(d_x)
print(d_h)

d_g = pycuda.gpuarray.arange(0, 10, 0.1, dtype = np.float32)
print(d_g)

d_w = d_w.fill(3)
print(d_w)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[0.         0.1        0.2        0.3        0.4        0.5
 0.6        0.7        0.8        0.90000004 1.         1.1
 1.2        1.3000001  1.4        1.5        1.6        1.7
 1.8000001  1.9        2.         2.1000

We do not have ```gpuarray.ones```, but we do have ```gpuarray.zeros``` and ```gpuarray.ones_like```. We try first ```gpuarray.zeros``` with single precision elements and add elementwise $1$.



In [23]:
d_x = 1 + gpuarray.zeros((32, 32), np.float32)
print(d_x)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


Now we make elementwise operations:

In [7]:
d_y = np.float32(3) * gpuarray.ones_like(d_x, np.float32)

d_z = d_y * pycuda.cumath.exp(1j * np.pi * d_x)

print(d_z)

[[-3.-2.6226832e-07j -3.-2.6226832e-07j -3.-2.6226832e-07j ...
  -3.-2.6226832e-07j -3.-2.6226832e-07j -3.-2.6226832e-07j]
 [-3.-2.6226832e-07j -3.-2.6226832e-07j -3.-2.6226832e-07j ...
  -3.-2.6226832e-07j -3.-2.6226832e-07j -3.-2.6226832e-07j]
 [-3.-2.6226832e-07j -3.-2.6226832e-07j -3.-2.6226832e-07j ...
  -3.-2.6226832e-07j -3.-2.6226832e-07j -3.-2.6226832e-07j]
 ...
 [-3.-2.6226832e-07j -3.-2.6226832e-07j -3.-2.6226832e-07j ...
  -3.-2.6226832e-07j -3.-2.6226832e-07j -3.-2.6226832e-07j]
 [-3.-2.6226832e-07j -3.-2.6226832e-07j -3.-2.6226832e-07j ...
  -3.-2.6226832e-07j -3.-2.6226832e-07j -3.-2.6226832e-07j]
 [-3.-2.6226832e-07j -3.-2.6226832e-07j -3.-2.6226832e-07j ...
  -3.-2.6226832e-07j -3.-2.6226832e-07j -3.-2.6226832e-07j]]


Complex numbers manipulations. Taking real and imaginary parts. 

In [8]:
d_y_real = d_y.real
d_y_imag = d_y.imag

print(d_y_real)
print(d_y_imag)

d_y = 1j * d_y
print(d_y)

d_y.conj(d_y)
# d_y = d_y.conj()
print(d_y)

[[3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]
 ...
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.+3.j 0.+3.j 0.+3.j ... 0.+3.j 0.+3.j 0.+3.j]
 [0.+3.j 0.+3.j 0.+3.j ... 0.+3.j 0.+3.j 0.+3.j]
 [0.+3.j 0.+3.j 0.+3.j ... 0.+3.j 0.+3.j 0.+3.j]
 ...
 [0.+3.j 0.+3.j 0.+3.j ... 0.+3.j 0.+3.j 0.+3.j]
 [0.+3.j 0.+3.j 0.+3.j ... 0.+3.j 0.+3.j 0.+3.j]
 [0.+3.j 0.+3.j 0.+3.j ... 0.+3.j 0.+3.j 0.+3.j]]
[[0.-3.j 0.-3.j 0.-3.j ... 0.-3.j 0.-3.j 0.-3.j]
 [0.-3.j 0.-3.j 0.-3.j ... 0.-3.j 0.-3.j 0.-3.j]
 [0.-3.j 0.-3.j 0.-3.j ... 0.-3.j 0.-3.j 0.-3.j]
 ...
 [0.-3.j 0.-3.j 0.-3.j ... 0.-3.j 0.-3.j 0.-3.j]
 [0.-3.j 0.-3.j 0.-3.j ... 0.-3.j 0.-3.j 0.-3.j]
 [0.-3.j 0.-3.j 0.-3.j ... 0.-3.j 0.-3.j 0.-3.j]]


Computing the power of real and complex arrays.

In [9]:
d_w     = d_y_real.__pow__(3)
print(d_w.real)

d_z     = pycuda.cumath.exp(1j * (np.pi / 2) * d_x)
d_w     = d_z.__pow__(2)
print(d_w)

[[27. 27. 27. ... 27. 27. 27.]
 [27. 27. 27. ... 27. 27. 27.]
 [27. 27. 27. ... 27. 27. 27.]
 ...
 [27. 27. 27. ... 27. 27. 27.]
 [27. 27. 27. ... 27. 27. 27.]
 [27. 27. 27. ... 27. 27. 27.]]
[[-1.-8.742278e-08j -1.-8.742278e-08j -1.-8.742278e-08j ...
  -1.-8.742278e-08j -1.-8.742278e-08j -1.-8.742278e-08j]
 [-1.-8.742278e-08j -1.-8.742278e-08j -1.-8.742278e-08j ...
  -1.-8.742278e-08j -1.-8.742278e-08j -1.-8.742278e-08j]
 [-1.-8.742278e-08j -1.-8.742278e-08j -1.-8.742278e-08j ...
  -1.-8.742278e-08j -1.-8.742278e-08j -1.-8.742278e-08j]
 ...
 [-1.-8.742278e-08j -1.-8.742278e-08j -1.-8.742278e-08j ...
  -1.-8.742278e-08j -1.-8.742278e-08j -1.-8.742278e-08j]
 [-1.-8.742278e-08j -1.-8.742278e-08j -1.-8.742278e-08j ...
  -1.-8.742278e-08j -1.-8.742278e-08j -1.-8.742278e-08j]
 [-1.-8.742278e-08j -1.-8.742278e-08j -1.-8.742278e-08j ...
  -1.-8.742278e-08j -1.-8.742278e-08j -1.-8.742278e-08j]]


Computing the ```abs``` of a complex array.



In [10]:
d_z     = (1 + 1j) * d_x
d_w     = d_z.__abs__()
print(d_w)

[[1.4142135 1.4142135 1.4142135 ... 1.4142135 1.4142135 1.4142135]
 [1.4142135 1.4142135 1.4142135 ... 1.4142135 1.4142135 1.4142135]
 [1.4142135 1.4142135 1.4142135 ... 1.4142135 1.4142135 1.4142135]
 ...
 [1.4142135 1.4142135 1.4142135 ... 1.4142135 1.4142135 1.4142135]
 [1.4142135 1.4142135 1.4142135 ... 1.4142135 1.4142135 1.4142135]
 [1.4142135 1.4142135 1.4142135 ... 1.4142135 1.4142135 1.4142135]]


Trigonometric and hyperbolic trigonometric functions of complex arrays, fundamental mathematical functions of complex arrays.

In [24]:
d_z     = pycuda.cumath.sin((1 + 1j) * d_x)
print(d_z)

d_z     = pycuda.cumath.cos((1 + 1j) * d_x)
print(d_z)

d_z     = pycuda.cumath.tan((1 + 1j) * d_x)
print(d_z)

d_z     = pycuda.cumath.sinh((1 + 1j) * d_x)
print(d_z)

d_z     = pycuda.cumath.cosh((1 + 1j) * d_x)
print(d_z)

d_z     = pycuda.cumath.tanh((1 + 1j) * d_x)
print(d_z)

d_z     = pycuda.cumath.exp((1 + 1j) * d_x)
print(d_z)

d_z     = pycuda.cumath.log((1 + 1j) * d_x)
print(d_z)

d_z     = pycuda.cumath.sqrt((1 + 1j) * d_x)
print(d_z)

[[1.2984576+0.63496387j 1.2984576+0.63496387j 1.2984576+0.63496387j ...
  1.2984576+0.63496387j 1.2984576+0.63496387j 1.2984576+0.63496387j]
 [1.2984576+0.63496387j 1.2984576+0.63496387j 1.2984576+0.63496387j ...
  1.2984576+0.63496387j 1.2984576+0.63496387j 1.2984576+0.63496387j]
 [1.2984576+0.63496387j 1.2984576+0.63496387j 1.2984576+0.63496387j ...
  1.2984576+0.63496387j 1.2984576+0.63496387j 1.2984576+0.63496387j]
 ...
 [1.2984576+0.63496387j 1.2984576+0.63496387j 1.2984576+0.63496387j ...
  1.2984576+0.63496387j 1.2984576+0.63496387j 1.2984576+0.63496387j]
 [1.2984576+0.63496387j 1.2984576+0.63496387j 1.2984576+0.63496387j ...
  1.2984576+0.63496387j 1.2984576+0.63496387j 1.2984576+0.63496387j]
 [1.2984576+0.63496387j 1.2984576+0.63496387j 1.2984576+0.63496387j ...
  1.2984576+0.63496387j 1.2984576+0.63496387j 1.2984576+0.63496387j]]
[[0.8337299-0.98889774j 0.8337299-0.98889774j 0.8337299-0.98889774j ...
  0.8337299-0.98889774j 0.8337299-0.98889774j 0.8337299-0.98889774j]
 [0.833

Other mathematical operations defined on real arrays.

In [25]:
d_z     = pycuda.cumath.asin(d_x)
print(d_z)

d_z     = pycuda.cumath.acos(d_x)
print(d_z)

d_z     = pycuda.cumath.atan(d_x)
print(d_z)

d_z     = pycuda.cumath.log10(d_x)
print(d_z)

d_z     = pycuda.cumath.fabs(-d_x)
print(d_z)

d_z     = pycuda.cumath.ceil(1.6 * d_x)
print(d_z)

d_z     = pycuda.cumath.floor(1.1 * d_x)
print(d_z)

[[1.5707964 1.5707964 1.5707964 ... 1.5707964 1.5707964 1.5707964]
 [1.5707964 1.5707964 1.5707964 ... 1.5707964 1.5707964 1.5707964]
 [1.5707964 1.5707964 1.5707964 ... 1.5707964 1.5707964 1.5707964]
 ...
 [1.5707964 1.5707964 1.5707964 ... 1.5707964 1.5707964 1.5707964]
 [1.5707964 1.5707964 1.5707964 ... 1.5707964 1.5707964 1.5707964]
 [1.5707964 1.5707964 1.5707964 ... 1.5707964 1.5707964 1.5707964]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.7853982 0.7853982 0.7853982 ... 0.7853982 0.7853982 0.7853982]
 [0.7853982 0.7853982 0.7853982 ... 0.7853982 0.7853982 0.7853982]
 [0.7853982 0.7853982 0.7853982 ... 0.7853982 0.7853982 0.7853982]
 ...
 [0.7853982 0.7853982 0.7853982 ... 0.7853982 0.7853982 0.7853982]
 [0.7853982 0.7853982 0.7853982 ... 0.7853982 0.7853982 0.7853982]
 [0.7853982 0.7853982 0.7853982 ... 0.7853982 0.7853982 0.7853982]]
[[0. 0. 0. ... 0. 0. 0.]
 [0

Conditional operations

In [26]:
h_x = np.zeros((5, 1), dtype = np.float32)
h_x[0] = 11
h_x[1] = -4
h_x[2] = 77
h_x[3] = -14
h_x[4] = 0

h_y = np.zeros((5, 1), dtype = np.float32)
h_y[0] = 12.3
h_y[1] = 11.4
h_y[2] = -7
h_y[3] = 0
h_y[4] = 12

d_x = pycuda.gpuarray.to_gpu(h_x)
d_y = pycuda.gpuarray.to_gpu(h_y)

d_h = pycuda.gpuarray.if_positive(d_x - d_y, d_x, d_y)
print(d_h)

d_h = pycuda.gpuarray.maximum(d_x, d_y)
print(d_h)

d_h = pycuda.gpuarray.minimum(d_x, d_y)
print(d_h)

[[12.3]
 [11.4]
 [77. ]
 [ 0. ]
 [12. ]]
[[12.3]
 [11.4]
 [77. ]
 [ 0. ]
 [12. ]]
[[ 11.]
 [ -4.]
 [ -7.]
 [-14.]
 [  0.]]


Reductions.

In [28]:
d_red = pycuda.gpuarray.sum(d_x)
print(d_red)

d_red = pycuda.gpuarray.max(d_x)
print(d_red)

d_red = pycuda.gpuarray.min(d_x)
print(d_red)

d_red = pycuda.gpuarray.dot(d_x, d_y)
print(d_red)

h_index = np.zeros((3, 1), dtype = np.int32)
h_index[0] = 0
h_index[1] = 3
h_index[2] = 4
d_index = pycuda.gpuarray.to_gpu(h_index)

d_red = pycuda.gpuarray.subset_sum(d_index, d_x)
print(d_red)

d_red = pycuda.gpuarray.subset_max(d_index, d_x)
print(d_red)

d_red = pycuda.gpuarray.subset_min(d_index, d_x)
print(d_red)

d_red = pycuda.gpuarray.subset_dot(d_index, d_x, d_y)
print(d_red)

d_x = 1j * d_x
d_red = pycuda.gpuarray.dot(d_x, d_x)
print(d_red)

70.0
77.0
-14.0
-449.30002
-3.0
11.0
-14.0
135.3
(-6262+0j)


Array scrambling.

In [15]:
h_x = np.zeros((5, 1), dtype = np.complex64)
h_x[0] = 11
h_x[1] = -4
h_x[2] = 77
h_x[3] = -14
h_x[4] = 0
d_x = pycuda.gpuarray.to_gpu(h_x)

h_index = np.zeros((3, ), dtype = np.int32)
h_index[0] = 3
h_index[1] = 4
h_index[2] = 0
d_index = pycuda.gpuarray.to_gpu(h_index)

d_x = pycuda.gpuarray.take(d_x, d_index)
print(d_x)

[-14.+0.j   0.+0.j  11.+0.j]


Casting and shape manipulations.

In [16]:
h_x = np.zeros((5, 1), dtype = np.float32)
h_x[0] = 11.2
h_x[1] = -4.3
h_x[2] = 77.6
h_x[3] = -14.1
h_x[4] = 0.4
d_x = pycuda.gpuarray.to_gpu(h_x)

d_x = d_x.astype(np.int32)
print(d_x)

[[ 11]
 [ -4]
 [ 77]
 [-14]
 [  0]]


In [17]:
h_x = np.zeros((8, 1), dtype = np.float32)
h_x[0] = 11.2
h_x[1] = -4.3
h_x[2] = 77.6
h_x[3] = -14.1
h_x[4] = 0.4
h_x[5] = 0.6
h_x[6] = -20
h_x[7] = -12.4
d_x = pycuda.gpuarray.to_gpu(h_x)

d_x = d_x.reshape((2, 4))
print(d_x)

[[ 11.2  -4.3  77.6 -14.1]
 [  0.4   0.6 -20.  -12.4]]


In [18]:
d_x = d_x.ravel()
print(d_x)

[ 11.2  -4.3  77.6 -14.1   0.4   0.6 -20.  -12.4]


In [19]:
h_x = np.zeros((2, 4, 1), dtype = np.float32)
h_x[0, 0, 0] = 11.2
h_x[1, 0, 0] = -4.3
h_x[0, 1, 0] = 77.6
h_x[1, 1, 0] = -14.1
h_x[0, 2, 0] = 0.4
h_x[1, 2, 0] = 0.6
h_x[0, 3, 0] = -20
h_x[1, 3, 0] = -12.4
d_x = pycuda.gpuarray.to_gpu(h_x)
print(d_x[:, :, :])

d_x = d_x.squeeze()
print(d_x)

[[[ 11.2]
  [ 77.6]
  [  0.4]
  [-20. ]]

 [[ -4.3]
  [-14.1]
  [  0.6]
  [-12.4]]]
[[ 11.2  77.6   0.4 -20. ]
 [ -4.3 -14.1   0.6 -12.4]]


Other floating point operations.

In [39]:
d_x = 1. + gpuarray.zeros((5, 1), np.float32)
d_y = 2. + gpuarray.zeros((5, 1), np.float32)

d_z = pycuda.cumath.fmod(d_x, d_y)
print(d_z)

d_z = pycuda.cumath.modf(d_x)
print(d_z)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32), array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32))


Array information.

In [30]:
print('Shape (dimensions, Matlab''s size)                : ', d_z.shape)
print('Type                                              : ', d_z.dtype)
print('Size (total number of elements)                   : ', d_z.size)
print('Size (total number of elements including padding) : ', d_z.mem_size)
print('Number of bytes                                   : ', d_z.nbytes)
print('Strides                                           : ', d_z.strides)
print('Array pointer                                     : ', d_z.ptr)
print('Row major?                                        : ', d_z.flags.c_contiguous)
print('Column major?                                     : ', d_z.flags.f_contiguous)
print('Any contiguity?                                   : ', d_z.flags.forc)
print(d_z.__cuda_array_interface__)

h_x = np.zeros((2, 4), dtype = np.float32)
h_x[0, 0] = 11.2
h_x[1, 0] = -4.3
h_x[0, 1] = 77.6
h_x[1, 1] = -14.1
h_x[0, 2] = 0.4
h_x[1, 2] = 0.6
h_x[0, 3] = -20
h_x[1, 3] = -12.4
d_x = pycuda.gpuarray.to_gpu(h_x)
print(d_x[1, 1 : 3])

Shape (dimensions, Matlabs size)                :  (32, 32)
Type                                              :  float32
Size (total number of elements)                   :  1024
View                     :  [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
Size (total number of elements including padding) :  1024
Number of bytes                                   :  4096
Strides                                           :  (128, 4)
Array pointer                                     :  140106782705664
Row major?                                        :  True
Column major?                                     :  False
Any contiguity?                                   :  True
{'shape': (32, 32), 'strides': (128, 4), 'data': (140106782705664, False), 'typestr': '<f4', 'stream': None, 'version': 3}
[-14.1   0.6]
